language: python
python:
  - 2.7
  - 3.4
install:
  - sudo apt-get -y update
  - cd lae_regression
  - pip install -r requirements.txt
  - python setup.py install
  - pip install nose
  - pip install codecov
script:
  #- nosetests
  nosetests --with-coverage
after_success:
  - codecov
  